version: '3.4'

services:
  assignment2:
    image: FixedAssetTracker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3100:3100
